### ISSUE TITLE
Performance on million-node datasets + hyperparameter tuning?

### ISSUE THREAD

**Issue by apoorvumang** [migalkin/NodePiece#1]
Hi

Really cool work! I was wondering whether you have results for million-node datasets such as WikiData5m or WikiKG 2, or does it take too long to preprocess those?

Also did you do any kind of hyperparameter search?

Thanks

**Comment by migalkin** [comment]
Hi, thanks for reaching out!

Yes, we are running some experiments internally on OGB WikiKG 2.

The graph is huge (2.5M nodes / 16M edges) and iGraph seems to be a bit of a bottleneck there - it is not parallelizable to multiple CPUs, so it always uses only one core even on a powerful cluster (although iGraph has a "batch"-mode for necessary functions). It is definitely a priority for us to have a parallelizable tokenization process over separate connected components (since we only look for nearest anchors).
Anyways, with this suboptimal single-core iGraph strategy, it took about 55 hours to obtain a vocab for WikiKG 2.

As to hyperparameters: yes, we experimented quite a lot - it depends on the encoder (MLP / Transformer) and graph structure - we listed the best configs in the Appendix of the paper.
